### ISSUE TITLE
Definition of Donen päivitys

### ISSUE THREAD

**Issue by ahojukka5** [ahojukka5/lukuvinkkikirjasto#4]
Meidän pitäisi tuo Definition of Done päivättää jotta se olisi konkreettisempi. Tässä esimerkkejä mitenkä muissa projekteissa on asiaa määritelty:

- https://github.com/sannahan/lukuvinkkikirjasto
- https://github.com/Marcestus/OhTu_miniprojekti
- https://github.com/Mazaalto/LukuvinkkisovellusRyhmaB
- https://github.com/MikkoHimanka/Lukuvinkit
- https://github.com/uradora/ohtu-miniprojekti-2021
- https://github.com/HJJHeinonen/OHTU-lukuvinkkikirjasto

Joitakin omia ehdotuksia:

- Jokaiselle luokalle vähintään yksi yksikkötesti
- Testikattavuus vähintään samaa luokkaa kuin koko projektissa, yli 80 % joka tapauksessa
- Checkstylen pitää mennä läpi

Mitäs muuta?

**Comment by jkotima** [comment]
- joku muu kuin koodin kirjoittaja(t) on katselmoinut koodin vois olla (eli joku toinen mergeää pullrequestin)

Toi joka luokan yksikkötesti ei mun mielestä välttämättä tarpeen, jos testautuu jonkun toisen testin kautta muutenkin
